tls:
  certificates:
    - certFile: /certs/rocky2.crt
      keyFile:  /certs/rocky2.key
  stores:
    default:
      defaultCertificate:
        certFile: /certs/rocky2.crt
        keyFile:  /certs/rocky2.key
